
# Site settings

# NB! Set your site's url, otherwise stuff will break :)

url: "http://www.yetanother.site"

# If you're hosting your site at a Project repository on GitHub pages
# (https://yourusername.github.io/repository-name)
# and NOT your user repository (https://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
#
# NB! Without this *nothing* will work, because it's used in every path :)

# baseurl:

# Google tracking id to track your visitors

#google-tracking-id: "UA-35880426-4"

# Forces https everywhere in your website, except when you serve it locally
# If you are not hosted on Github Pages, and your host doesn't support https
# then you should disable it

# force-https: False

#############
# HTML Head #
#############

lang: "en"
author: "@andygauge"
title: "Yet Another Site"
description: "eCommerce and website development"
keywords: "ruby, development, agency, yet another, consultancy, design"
favicon: "/img/favicon.ico"
404-img: "/img/labtocat.png"

################
# Header layout #
################

black-favicon: "/img/black-lab-glass.ico"

background-img: /img/look-up.jpg

##############################
# Dynamic Text on the Header    #
##############################

dynamic-typing: True
shuffle: True # Shuffle the lines.
loop: True
loop-count: False # Set False for infinite loop, or set any number for finite loop.
type-speed: 100
start-delay: 200
delete-delay: 1000
lines: # You can add HTML Tags in the Text
  - text: "module ApplicationHelper</br>
<span class='code_tab' />def pb_menu_item (controller_name, path: nil, display: controller_name.capitalize)</br>
<span class='code_2tab'/></span>path ||= send('#{controller_name.downcase}_path') </br>
<span class='code_2tab'/>'li class='nav-item #{' active' if current_page?(path)}'></br>
<span class='code_3tab'/>a class='nav-link pb-navbar-link'href='#{path}'#{display}/a</br>
<span class='code_2tab'/>/li'.html_safe</br>
<span class='code_tab'/>end</br>
<span class='code_tab'/>def pb_bottom_menu(items)</br>
<span class='code_2tab'/>items.inject('') {|collects, item| </br>
<span class='code_3tab'/>collects + 'li class='nav-item'>' + link_to(item.titleize, send('#{item}_path'), class: 'nav-link') + '/li'</br>
<span class='code_2tab'/>}.html_safe</br>
<span class='code_tab'/>end</br>
end"
  - text: "
$ -></br>
<span class='code_tab'/>$('#subset_filter').on('input', -></br>
<span class='code_2tab'/>subsetFilter = $(this).val().toLowerCase()</br>
<span class='code_2tab'/>if subsetFilter != ''</br>
<span class='code_3tab'/>$('.checkbox-inline[data-keywords]').addClass('hidden')</br>
<span class='code_4tab'/>.filter( -></br>
<span class='code_4tab'/>$(this).attr('data-keywords')</br>
<span class='code_5tab'/>.lastIndexOf(subsetFilter) != -1</br>
<span class='code_4tab'/>).removeClass('hidden')</br>
<span class='code_2tab'>)</br>
<span class='code_tab'/>$('#subset_more').on('click', -></br>
<span class='code_2tab'/>$('.checkbox-inline[data-keywords].hidden').removeClass('hidden')</br>
<span class='code_2tab'/>)</br>
<span class='code_tab'/>$('.checkbox-inline[data-keywords].hidden input:checked').parent().removeClass('hidden')"
  - text: "
func (s *SlackAPI) SendToSlack() error {</br>
<span class='code_tab'/>if s.Token == '' {</br>
<span class='code_2tab'/>return errors.New(fmt.Sprintf('API_KEY must be configured for a Slack Message.  %s failed', s))</br>
<span class='code_tab'/>}</br>
<span class='code_tab'/>if params, err := json.Marshal(s); err == nil {</br>
<span class='code_2tab'/>resp, err := http.Post(SlackApiUrl, 'application/json', bytes.NewBuffer(params))</br>
<span class='code_2tab'/>if err != nil { return err }</br>
<span class='code_2tab'/>defer resp.Body.Close()</br>
<span class='code_2tab'/>body, err := ioutil.ReadAll(resp.Body)</br>
<span class='code_2tab'/>if err != nil { return err }</br>
<span class='code_2tab'/>var jsonResponse map[string]interface{}</br>
<span class='code_2tab'/>err = json.Unmarshal(body, jsonResponse)</br>
<span class='code_2tab'/>if err != nil { return err }</br>
<span class='code_2tab'/>if jsonerr,ok := jsonResponse['error']; ok == false {</br>
<span class='code_3tab'/>return errors.New(jsonerr.(string)) }</br>
<span class='code_tab'/>} else { return err }</br>
<span class='code_tab'/>return nil }"
me-img: 'img/me-dark.jpg'
##############################
# Color the browser elements #
##############################
color-browser: "#000000"
apple-status-bar-style: "black"

################
# Web app mode #
################

web-app-mode: True

# Icons for Web App mode

icon-36p: "/img/web-app/icon-36p.png"
icon-48p: "/img/web-app/icon-48p.png"
icon-72p: "/img/web-app/icon-72p.png"
icon-96p: "/img/web-app/icon-96p.png"
icon-144p: "/img/web-app/icon-144p.png"
icon-192p: "/img/web-app/icon-192p.png"

########
# Blog #
########

post-preview-words: 96

paginate: 5

email-share: False
fb-share: False
twitter-share: False
linkedin-share: False
reddit-share: False
google-plus-share: False
tumblr-share: False
pinterest-share: False
pocket-share: False
vkontakte-share: False

disqus-shortname: "andygauge"

syntax-highlight: True

############
# Timeline #
############

events:
  - image: /img/business_name.png
    date: "January 2018"
    description: "Launched Yet Another site"
  - image: /img/gear.png
    date: "Feburary 2016"
    description: "Launched Yet Another Site"
  - image: /img/prayer-beads.png
    date: "October 2015"
    description: "Launched Praybook"
  - image: /img/chalkboard.png
    date: "January 2013"
    description: "First Speaking: MongoDB"
  - image: /img/red-steam.jpg
    date: "November 2011"
    description: "Learned Ruby / Rails"

# First image of the Timeline

timeline-img: "/img/typewriter.jpg"

###########
# Contact #
###########

email: "us@yetanother.site"


##################
# Social Buttons #
##################

social:
  - title: "twitter"
    url: "https://twitter.com/andygauge"
  - title: "github"
    url: "https://github.com/andygauge"
  - title: "rss"
    url: "/feed.xml"

############
# 404 page #
############

404-img: "/img/labtocat.png"

################################################################################

# NB! Tread carefully if you want to change the variables below this point!

# Sections shown in the index page

pages_list:
  Faq: 'faq'
  Blog: 'latest-post'
  Samples: 'samples'
  Timeline: 'timeline'
  Contact: 'contact'

# Exclusion list from the generated _site

exclude: ["LICENSE", "README.md", "CONTRIBUTING", "CONTRIBUTORS", "scripts"]

# Pagination path

paginate_path: "blog/page:num/"

# Enable minification SASS

sass:
  style: compressed

gems:
  - jekyll-paginate
